name: doxygen
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
      - uses: mattnotmitt/doxygen-action@v1
        with:
           doxyfile-path: doc/Doxyfile
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: ${{ github.event.head_commit.message }}
          disable_nojekyll: true
          publish_branch: gh-pages
          force_orphan: true
          publish_dir: html
